Span interface definition, Span model definition added
dotnetcore/mocha pull request #25
Opened 2023-10-18 05:47 UTC by KawhiWei

1. Changes within the Mocha.Storage MysqlSpanWrite, EntityFrameworkSpanWrite MySQLSpanReader EntityFrameworkSpanReader
2. Changes within the Mocha.Core.Storage ISpanWriter, ISpanWrite
3. Add MochaContext definition

2023-10-18 06:32 UTC, liuhaoyang requested changes

2023-10-18 06:32 UTC, liuhaoyang commented on src/Mocha.Core/Storage/ISpanWriter.cs
> +    Task<bool> WriteAsync(Span span);
更好的做法是传递 IEnumerable<Span>而不是 Span，因为许多存储在批量写入时性能更好。

2023-10-18 06:32 UTC, liuhaoyang commented on src/Mocha.Core/Storage/ISpanWriter.cs
> +    bool Write(Span span);
只提供一个异步的API就够用了

2023-10-18 06:32 UTC, liuhaoyang commented on src/Mocha.Distributor/Services/OTelTraceExportService.cs
> +        request.ResourceSpans.First().ScopeSpans.First().Spans.First().SpanId.ToString();
删除测试代码

2023-10-18 06:32 UTC, liuhaoyang commented on src/Mocha.Core/Storage/ISpanReader.cs
> -
license header 被删除了吗

2023-10-18 06:38 UTC, liuhaoyang commented on src/Mocha.Core/Storage/ISpanReader.cs
查询还需要支持 tags 、Duration 等条件

2023-10-18 06:38 UTC, liuhaoyang requested changes

2023-10-18 06:38 UTC, liuhaoyang commented on src/Mocha.Storage/EntityFrameworkStorage/EntityFrameworkSpanReader.cs
> +public class EntityFrameworkSpanReader:ISpanReader
代码格式化

2023-10-18 06:38 UTC, liuhaoyang commented on src/Mocha.Storage/EntityFrameworkStorage/EntityFrameworkSpanWriter.cs
> +{
代码格式化

2023-10-18 12:17 UTC, eventhorizon-cli commented on src/Mocha.Core/Model/Trace/Span.cs
> +    public string TraceId { get; private set; }
这边不要定义private 的set，不是只给ef用的

2023-10-18 12:17 UTC, eventhorizon-cli commented on src/Mocha.Core/Model/Trace/Span.cs
> +    public int SpanKind { get; private set; }
SpanKind 定义成枚举

2023-10-18 12:17 UTC, eventhorizon-cli commented on src/Mocha.Core/Model/Trace/Span.cs
> +{
为什么各个模型之间的关联关系都没有，都是散的

2023-10-18 13:40 UTC, KawhiWei commented on src/Mocha.Core/Model/Trace/Span.cs
> +{
@eventhorizon-cli 你说的关系是指模型与模型之间的关系？

2023-10-18 13:40 UTC, KawhiWei commented on src/Mocha.Core/Model/Trace/Span.cs
> +    public int SpanKind { get; private set; }
> SpanKind 定义成枚举

get

2023-10-18 13:45 UTC, KawhiWei commented on src/Mocha.Core/Storage/ISpanReader.cs
> 查询还需要支持 tags 、Duration 等条件

get

2023-10-20 08:09 UTC, tsaiggo commented on src/Mocha.Core/Storage/ISpanWriter.cs
> +    Task<bool> WriteAsync(IEnumerable<Span> span);
直接叫Span好像有点不是很好

2023-10-23 02:44 UTC, liuhaoyang requested changes

2023-10-23 02:44 UTC, liuhaoyang commented on src/Mocha.Core/Mocha.Core.csproj
> +    </ItemGroup>
反向依赖了。core 是基础模块，不能依赖功能模块

2023-10-23 02:44 UTC, liuhaoyang commented on src/Mocha.Core/Storage/Query/TraceReadQuery.cs
> +    public long StartTimeBucket { get; set; } = default!;
叫 `xxxTimestamp` 更好一些

2023-10-23 02:44 UTC, liuhaoyang commented on src/Mocha.Distributor/Program.cs
> -
把header删掉了吗

2023-10-23 02:44 UTC, liuhaoyang commented on src/Mocha.Distributor/Services/OTelTraceExportService.cs
>  using Grpc.Core;
把header删掉了吗

2023-10-23 02:47 UTC, eventhorizon-cli commented on src/Mocha.Core/Enums/SpanKindEnum.cs
> +public enum SpanKindEnum
就叫SpanKind，别带Enum后缀了，然后这边也还没定义完

2023-10-23 02:47 UTC, eventhorizon-cli commented on src/Mocha.Core/Mocha.Core.csproj
> +    <ItemGroup>
为什么会在core里引用Distributor

2023-10-23 02:47 UTC, eventhorizon-cli commented on src/Mocha.Core/Storage/ISpanWriter.cs
> +    Task<bool> WriteAsync(IEnumerable<Span> span);
入参应该叫spans

2023-10-23 02:47 UTC, eventhorizon-cli commented on src/Mocha.Core/Storage/Query/TraceReadQuery.cs
> +{
default!是表示这个不可能为空，不要这么写，不利于<Nullable>的check

2023-10-23 02:47 UTC, eventhorizon-cli commented on src/Mocha.Storage/EntityFrameworkStorage/Trace/Span.cs
> +{
不要写default!

2023-10-23 02:47 UTC, eventhorizon-cli commented on src/Mocha.Storage/Mocha.Storage.csproj
> -
和其他project一样，开启Nullable <Nullable>enable</Nullable>

2023-10-23 11:54 UTC, KawhiWei commented on src/Mocha.Storage/Mocha.Storage.csproj
> -
> 和其他project一样，开启Nullable enable

开了的

2023-10-23 12:18 UTC, liuhaoyang requested changes

2023-10-23 12:18 UTC, liuhaoyang commented on src/Mocha.Distributor/Program.cs
> +// The.NET Core Community licenses this file to you under the MIT license.
注意空格

2023-10-23 12:24 UTC, KawhiWei commented on src/Mocha.Distributor/Program.cs
> +// The.NET Core Community licenses this file to you under the MIT license.
> 注意空格

![image](https://github.com/dotnetcore/mocha/assets/46982191/4baf4fce-2287-4c93-9d28-11b8a998c8cf)
我晓得，这里就少了空格

2023-10-23 13:50 UTC, merged